### ISSUE TITLE
Cannot find revel library 1.2.0 sources anywhere

### ISSUE THREAD

**Issue by ghost** [gesellkammer/lambda#1]
The revel library sources v1.2.0, corresponding to the file lamba/src/revel.h cannot be found (anywhere?) on the Internet. Tried archive.org on the sourceforge project, which is now defunct, with no success.
I have found revel 1.1.0 sources though.
If you still have revel 1.2.0 sources around, I would suggest you push the files in lambda (they are GPL). Without them it is impossible to compile lambda.
There are not so many easy to use acoustics simulation codes on the Internet. Too bad I cannot try yours.
BR.

**Comment by gesellkammer** [comment]
The library is already there, in dependencies
